// Generated by Wrangler by running `wrangler types src/worker-configuration.d.ts --env-interface CloudflareBindings`

interface CloudflareBindings {
  Lobby: DurableObjectNamespace<import('./index').Lobby>;
  Signaling: DurableObjectNamespace<import('./index').Signaling>;
  DB: D1Database;
}
